// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL9CbbfbeoyhxWFSYoViXxLLw7qPG0F_A',
    appId: '1:1044804767976:web:ea37478bb9a8a7e266f95d',
    messagingSenderId: '1044804767976',
    projectId: 'hanbit-6219d',
    authDomain: 'hanbit-6219d.firebaseapp.com',
    storageBucket: 'hanbit-6219d.appspot.com',
    measurementId: 'G-QHPR47V0YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6oYvHYh5zD02j4TLxbPS88VeMMT-zWMo',
    appId: '1:1044804767976:android:4fa865d148ccc9ea66f95d',
    messagingSenderId: '1044804767976',
    projectId: 'hanbit-6219d',
    storageBucket: 'hanbit-6219d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIM_MV5N0J7lWt2KzsJYICjhzjnF7IEpk',
    appId: '1:1044804767976:ios:2527f454ab1afec466f95d',
    messagingSenderId: '1044804767976',
    projectId: 'hanbit-6219d',
    storageBucket: 'hanbit-6219d.appspot.com',
    iosBundleId: 'com.example.hanbitDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIM_MV5N0J7lWt2KzsJYICjhzjnF7IEpk',
    appId: '1:1044804767976:ios:2d0cb4b24af14e0966f95d',
    messagingSenderId: '1044804767976',
    projectId: 'hanbit-6219d',
    storageBucket: 'hanbit-6219d.appspot.com',
    iosBundleId: 'com.example.hanbitDirectory.RunnerTests',
  );
}
