# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test

  build:
    name: "Build Android client"
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # or: 'beta', 'dev' or 'master'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --dart-define=PLANNING_CENTER_APPLICATION_ID=${{ secrets.PLANNING_CENTER_APPLICATION_ID }} --dart-define=PLANNING_CENTER_SECRET=${{ secrets.PLANNING_CENTER_SECRET }}
      - run: flutter build appbundle

  ios-build:
    name: "Build iOS client"
    needs: test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign --dart-define=PLANNING_CENTER_APPLICATION_ID=${{ secrets.PLANNING_CENTER_APPLICATION_ID }} --dart-define=PLANNING_CENTER_SECRET=${{ secrets.PLANNING_CENTER_SECRET }}

  macos-build:
    name: "Build macOS client"
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      - run: flutter config --enable-macos-desktop
      - run: flutter build macos --dart-define=PLANNING_CENTER_APPLICATION_ID=${{ secrets.PLANNING_CENTER_APPLICATION_ID }} --dart-define=PLANNING_CENTER_SECRET=${{ secrets.PLANNING_CENTER_SECRET }}